version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: "${APP_NAME}-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: "${APP_NAME}-mysql"
    restart: unless-stopped
    volumes:
      - ./docker/mysql:/var/lib/mysql
    tty: true
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  mysql-testing:
    image: mysql:5.7.29
    container_name: "${APP_NAME}-mysql-testing"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: test
      SERVICE_NAME: mysql-testing
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${APP_NAME}-php"
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: "${APP_NAME}-composer"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: "${APP_NAME}-npm"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]

  npx:
    image: node:13.7
    container_name: "${APP_NAME}-npx"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npx"]

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${APP_NAME}-artisan"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel
